baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'CMFW Media'

disableKinds = ['taxonomy', 'term']

[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files

# Enable SASS processing
[build]
  writeStats = true
  [build.processing]
    sass = true
